name: checker

on:
  push:
    paths:
      - 'src/**.py'

jobs:
  checker:
    name: Check repo for issues
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2

      - name: Set up enviroment
        run: |
          sudo apt-get install python3 python3-tk
          sudo pip install -r requirements-dev.txt

      - name: Run flake8 linter
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run pytest tests
        run: |
          pytest
